# fly.toml app configuration file generated for fzm-discord-bot on 2025-12-24T22:28:38+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fzm-discord-bot'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_PATH = '/data/bot.db'
  LOG_LEVEL = 'INFO'

[[mounts]]
  source = 'bot_data'
  destination = '/data'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
